/**
 * Camunda Platform REST API
 * OpenApi Spec for Camunda Platform REST API.
 *
 * OpenAPI spec version: 7.13.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface ExtendLockOnExternalTaskDto { 
    /**
     * The ID of a worker who is locking the external task.
     */
    workerId?: string;
    /**
     * An amount of time (in milliseconds). This is the new lock duration starting from the current moment.
     */
    newDuration?: number;
}