/**
 * Camunda Platform REST API
 * OpenApi Spec for Camunda Platform REST API.
 *
 * OpenAPI spec version: 7.13.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ExceptionDto } from './exceptionDto';

export interface ParseExceptionDto { 
    /**
     * An exception class indicating the occurred error.
     */
    type?: string;
    /**
     * A detailed message of the error.
     */
    message?: string;
}