/**
 * Camunda Platform REST API
 * OpenApi Spec for Camunda Platform REST API.
 *
 * OpenAPI spec version: 7.13.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { HistoricProcessInstanceQueryDto } from './historicProcessInstanceQueryDto';
import { ProcessInstanceQueryDto } from './processInstanceQueryDto';

export interface ProcessInstanceSuspensionStateAsyncDto { 
    /**
     * A Boolean value which indicates whether to activate or suspend a given process instance. When the value is set to true, the given process instance will be suspended and when the value is set to false, the given process instance will be activated.
     */
    suspended?: boolean;
    /**
     * A list of process instance ids which defines a group of process instances which will be activated or suspended by the operation.
     */
    processInstanceIds?: Array<string>;
    processInstanceQuery?: ProcessInstanceQueryDto;
    historicProcessInstanceQuery?: HistoricProcessInstanceQueryDto;
}