export * from './condition.service';
import { ConditionService } from './condition.service';
export * from './deployment.service';
import { DeploymentService } from './deployment.service';
export * from './engine.service';
import { EngineService } from './engine.service';
export * from './eventSubscription.service';
import { EventSubscriptionService } from './eventSubscription.service';
export * from './externalTask.service';
import { ExternalTaskService } from './externalTask.service';
export * from './message.service';
import { MessageService } from './message.service';
export * from './metrics.service';
import { MetricsService } from './metrics.service';
export * from './processDefinition.service';
import { ProcessDefinitionService } from './processDefinition.service';
export * from './processInstance.service';
import { ProcessInstanceService } from './processInstance.service';
export * from './schemaLog.service';
import { SchemaLogService } from './schemaLog.service';
export * from './signal.service';
import { SignalService } from './signal.service';
export * from './task.service';
import { TaskService } from './task.service';
export * from './taskAttachment.service';
import { TaskAttachmentService } from './taskAttachment.service';
export * from './taskComment.service';
import { TaskCommentService } from './taskComment.service';
export * from './taskIdentityLink.service';
import { TaskIdentityLinkService } from './taskIdentityLink.service';
export * from './taskLocalVariable.service';
import { TaskLocalVariableService } from './taskLocalVariable.service';
export * from './taskVariable.service';
import { TaskVariableService } from './taskVariable.service';
export * from './version.service';
import { VersionService } from './version.service';
export const APIS = [ConditionService, DeploymentService, EngineService, EventSubscriptionService, ExternalTaskService, MessageService, MetricsService, ProcessDefinitionService, ProcessInstanceService, SchemaLogService, SignalService, TaskService, TaskAttachmentService, TaskCommentService, TaskIdentityLinkService, TaskLocalVariableService, TaskVariableService, VersionService];
